content:
  - name: posts
    label: Posts
    type: collection
    path: 'src/content/blog'
    view:
      fields: [ title, description ]
    fields:
      - name: title
        label: Title
        type: string
      - name: description
        label: Description
        type: string
      - name: body
        label: Body
        type: rich-text